Check go fmt in the PR

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -53,7 +53,7 @@ jobs:
     - name: Set up Go
       uses: actions/setup-go@v2-beta
       with:
-        go-version: 1.13.8
+        go-version: 1.14.2
       id: go
 
     - uses: actions/cache@v1
@@ -62,6 +62,15 @@ jobs:
         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
         restore-keys: |
           ${{ runner.os }}-go-
+
+    - name: Check code format
+      run: |
+        if [[ $(go fmt ./...) ]]; then
+          echo "go fmt check failed"
+          exit 1
+        else
+          echo "go fmt check success"
+        fi
 
     - name: Build
       run: |
@@ -78,7 +87,7 @@ jobs:
     - name: Set up Go
       uses: actions/setup-go@v2-beta
       with:
-        go-version: 1.13.8
+        go-version: 1.14.2
       id: go
 
     - uses: actions/cache@v1
@@ -87,6 +96,15 @@ jobs:
         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
         restore-keys: |
           ${{ runner.os }}-go-
+
+    - name: Check code format
+      run: |
+        if [[ $(go fmt ./...) ]]; then
+          echo "go fmt check failed"
+          exit 1
+        else
+          echo "go fmt check success"
+        fi
 
     - name: Build
       run: |
