Check go fmt in the PR (#411)
* Check go fmt in the PR

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -51,9 +51,9 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Set up Go
-      uses: actions/setup-go@v2-beta
+      uses: actions/setup-go@v2.0.3
       with:
-        go-version: 1.13.8
+        go-version: 1.14.2
       id: go
 
     - uses: actions/cache@v1
@@ -62,6 +62,16 @@ jobs:
         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
         restore-keys: |
           ${{ runner.os }}-go-
+
+    - name: Check code format
+      run: |
+        cd kubectl-cloudflow
+        if [[ $(go fmt ./...) ]]; then
+          echo "go fmt check failed"
+          exit 1
+        else
+          echo "go fmt check success"
+        fi
 
     - name: Build
       run: |
@@ -76,9 +86,9 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Set up Go
-      uses: actions/setup-go@v2-beta
+      uses: actions/setup-go@v2.0.3
       with:
-        go-version: 1.13.8
+        go-version: 1.14.2
       id: go
 
     - uses: actions/cache@v1
